### ISSUE TITLE
0.2 isn't transpiled

### ISSUE THREAD

**Issue by muffinresearch** [declandewet/common-tags#11]
This causes errors when trying to use it.

**Comment by muffinresearch** [comment]
Thanks - this is fixed by 0.0.3

**Comment by declandewet** [comment]
Thanks for letting me know @muffinresearch - I've had a number of issues with connectivity (power outages and continuous thunder storms) and have had higher priority work so unfortunately I haven't been able to devote much time to this project, but I am currently implementing a better build step that involves [Semantic Release](http://npmjs.org/package/semantic-release) so this issue will be avoided in future :)
