### ISSUE TITLE
oneLineTrim does not trim lines if there is no leading space on a subsequent line.

### ISSUE THREAD

**Issue by bsbates** [declandewet/common-tags#110]
If I have a top level block of code that looks like this:

```
const myString = oneLineTrim`
hello
world
`
```

This will not properly combine the lines into a single line.
If you look at the regex for oneLineTrim, it appears to need at least one space after the newline:
```
replaceResultTransformer(/(?:\n\s+)/g, '')
```

**Comment by fatfisz** [comment]
I can confirm that this is still happening. Will fix that soon, hopefully.
