### ISSUE TITLE
support simple string

### ISSUE THREAD

**Issue by yairper** [declandewet/common-tags#118]
I really like using this pkg, and I really need sometimes to use the same great functions for strings,
currently I do `oneLine([someString])`

Can you please add support for strings so we could do `oneLine(someString)`?
Thanks

**Comment by fatfisz** [comment]
Hi, it seems it would be possible. I'll try to get this feature in in a few days.

**Comment by fatfisz** [comment]
Keep your fingers crossed, the new feature is coming to town! I'll try to finish it at tomorrow at latest and then publish it ASAP.

**Comment by declandewet** [comment]
This was added in #132 so I'm closing the issue.

**Comment by yairper** [comment]
Cool, thanks :-)
