### ISSUE TITLE
1.5.0 breaking changes

### ISSUE THREAD

**Issue by thepheer** [declandewet/common-tags#128]
`stripIndents` now replaces multiple newlines with a single one.

```js
console.log(stripIndents`
a
b

c
`);
```

1.4.0 output:

```
a
b

c
```

1.5.0 output:

```
a
b
c
```

**Comment by fatfisz** [comment]
The breaking change was introduced in #127; unfortunately there were no tests for that case. I added some and fixed the problem, will be releasing soon.

**Comment by fatfisz** [comment]
Fix released in 1.5.1!

**Comment by thepheer** [comment]
Awesome! 🎉
