### ISSUE TITLE
Objects call their valueOf methods instead of toString methods.

### ISSUE THREAD

**Issue by dragonfire535** [declandewet/common-tags#143]
When converting objects into strings that have a custom `toString` method, I've noticed the lib calls `valueOf` instead. I don't know if this is intentional, but it really is confusing if you aren't expecting this behavior.

```js
console.log(stripIndents`
    ${obj} is cool!
`);
```

Assuming obj has a `valueOf` that returns "1" and a `toString` that returns "2", the `valueOf` gets called, which in normal template literals is not the case.

**Comment by fatfisz** [comment]
I'll investigate this.

**Comment by fatfisz** [comment]
Ok, I've got it - it was quite hard to track. I'll prepare a MR, keep your fingers crossed for a fast release!
