### ISSUE TITLE
Generate built files for CDN use

### ISSUE THREAD

**Issue by erquhart** [declandewet/common-tags#146]
Awesome project here! I had just finished reworking a bunch of examples for Netlify CMS using `stripIndent` when I realized there's no way to "just use it" via a CDN like unpkg.com. Have you considered providing built files?

**Comment by fatfisz** [comment]
@erquhart Could you take a look at the PR I added (#150)? Just want to make sure that everything that's needed is included there.

**Comment by erquhart** [comment]
Awesome, thanks for this @fatfisz!!
