### ISSUE TITLE
Post-process output of other tag functions?

### ISSUE THREAD

**Issue by rauschma** [declandewet/common-tags#16]
Occasionally, it’d be nice if one could dedent the output of another tag function, like this:

```js
stripIndent(String.raw)`
    abcdefg
`;
```

That could be achieved by making all functions behave differently if the first (and only) parameter is a function.

**Comment by declandewet** [comment]
@rauschma 

Would this feature just be syntactic sugar for this...?

```js
stripIndent`${String.raw`
    abcdefg
`}`
```

If so, I believe this is possible by doing something like

```js
function myTag (...args) { // caller tag definition
  if (typeof args[0] === 'function' && args.length === 1) {
    const tag = args.shift() // passed tag reference
    return (template, ...expressions) => {
      return myTag`${tag(template, ...expressions)}`
    }
  }
  const template = args.shift()
  const expressions = args
  let result = template.reduce((result, part, index) => {
    let expression = expressions[index - 1]
    // do something with the expression
    return result + expression + part
  })
  // do something with the final result
  return result
}

/*
usage:
  myTag(String.raw)`
    example tag
  `
*/
```

Or do you see it working differently?

The example above parses the template with the passed reference tag that is supplied to the caller tag as the first argument, and the caller tag then parses the result as if it were one sole expression, but it might be worthwhile to investigate a means of parsing each individual expression separately.

For example, suppose we had a `reverseExpressions` tag (for brevity) that reversed the text character order of a string expression:

```js
reverseExpressions`foo ${'bar'}` // => 'foo rab'
```

Of the following two (hypothetically) possible outputs, which is more ideal?

Output 1:
```js
reverseExpressions(String.raw)`foo\n${'bar'}` // => 'rabn\oof'
```

Output 2:
```js
reverseExpressions(String.raw)`foo\n${'bar'}` // => 'foo\nrab'
```

The first one is pretty easy (refer to the above example), but I'm not sure how to accomplish the second without using a transducer interface of some kind, or building a middleware layer (vastly changing the API surface of your example), which in my opinion is a little out of scope for this module

**Comment by rauschma** [comment]
I’d simply treat …

```js
reverseExpressions(String.raw)`whatever`
```

… as a more convenient syntax for …

```js
reverseExpressions(String.raw`whatever`)
```

**Comment by rauschma** [comment]
Your code for `myTag()` looks fine, but I’d expect there to be a helper function (e.g. `helperFunc()`) somewhere (that performs the actual work, on a single string). Then you can do:

```js
  if (args.length === 1 && typeof args[0] === 'function') {
    const tagFunc = args[0];
    return (...tagFuncArgs) => {
      return helperFunc(tagFunc(...tagFuncArgs));
    }
  }
```

**Comment by declandewet** [comment]
I see what you mean. I get the feeling that the `tags` function I have that accepts a settings object isn't future friendly. While I could implement this right away, it might be better to start thinking about implementing a re-usable class that can be used to compose a list of transformers into a custom tag. I think I have something in mind for this already. :) I'll get right on it as soon as I have some free time!

**Comment by rauschma** [comment]
Interesting thought. Makes a lot of sense.

FWIW: This is code that I’ll add to the blog post (and explain how it works) so that people see how to write tag functions.

```js
// TODO: properly indent substitutions (prefix the embedder’s indent)
// TODO: join() Arrays in substitutions

function countIndent(str) {
    let indent = 0;
    for (let i=0; i<str.length; i++) {
        const ch = str[i];
        if (ch !== ' ' && ch !== '\t') {
            break;
        }
    }
    return indent;
}

function dedentString(str) {
    const lines = str.split(/\r?\n/);
    if (lines.length === 0) return str;
    const indents = lines.map(line => countIndent(line));
    const minIndent = Math.min(...indents);
    const dedentedLines = lines.map(line => line.slice(indent));
    return dedentedLines.join('\n');
}
function collect(templateStrings, substitutions) {
    let result = templateStrings[0];
    for (let i=1; i<templateStrings.length; i++) {
        result += String(substitutions[i-1]);
        result += templateStrings[i];
    }
    return result;
}
function dedent(...args) {
    if (args.length === 1 && typeof args[1] === 'function') {
        const tagFunc = args[0];
        return (...tagFuncArgs) => {
            return dedentString(tagFunc(...tagFuncArgs));
        }
    }
    return dedentString(collect(...args));
}
```

**Comment by declandewet** [comment]
I've just come across another utility library that has a similar feature with a different syntax. Instead of calling the last tag as a function, you do this:

```js
oneLine.trim`

  foo
  baz

`
//=> "foo bazz"
```

The benefit this syntax has over the one you've proposed is that theoretically you can chain as many tags together as you want, as long as they support the interface to do so. Your proposal limits the amount of tags in the pipeline to two. I'll have to investigate this eventually, knowing my own tendency to be curious, but in the meantime when I submit my refactors to the core (when I get a chance), the syntax you've proposed here will be supported.

**Comment by declandewet** [comment]
@rauschma The syntax you've proposed is now included in the latest release :)
