### ISSUE TITLE
Optionally escape inserted content

### ISSUE THREAD

**Issue by rauschma** [declandewet/common-tags#18]
It’d be nice to have the option to escape inserted content (you’d only need to detect a prefixed dollar sign):

```js
const name = '<Jane>';
console.log(html`Name: $${name}`);
    // Name: &lt;Jane&gt;
```

The function that escapes could be configurable. One simple implementation:

```js
function htmlEscape(str) {
    return str.replace(/&/g, '&amp;') // first!
              .replace(/>/g, '&gt;')
              .replace(/</g, '&lt;')
              .replace(/"/g, '&quot;')
              .replace(/'/g, '&#39;')
              .replace(/`/g, '&#96;');
}
```

**Comment by declandewet** [comment]
I'm a little concerned about the dollar-sign syntax. It seems it might occasionally produce unwanted side-effects when the developer's intention is to explicitly use a dollar sign for formatting purposes, like when displaying currency, for example.

Is there any reason why you couldn't use the escape function in the expression itself?:

```js
html`Name: ${htmlEscape(name)}`
```

**Comment by rauschma** [comment]
Good point! I’d find some kind of special syntax convenient, like in most templating engines.

**Comment by declandewet** [comment]
This would be a breaking change, but what are your thoughts on escaping by default and using an exclamation mark to denote substitutions that should not be escaped? My reasoning being that an exclamation mark is rarely ever found at the beginning of a word and is rarely preceded by a space.

For example:

```js
const name = "<Jane>"
html`
  <div>Name: ${name}</div>
  <div>Name: !${name}</div>
`
// =>
//   <div>Name: &lt;Jane&gt;</div>"
//   <div>Name: <Jane></div>
```

**Comment by declandewet** [comment]
On second thoughts, I'm opposed to this change. Here's my reasoning:

DSLs are evil. Very often, they are far too limited and developers end up writing hacks around the limitations of the DSL which would be time completely wasted on work they wouldn't have to do had they just used bare syntax or a templating engine from the beginning.

I am also not convinced that ES2015 template strings were intended to be used as template engines. They might be one of the utility tools used to _create the foundation of_ a templating engine, but not to be used as templating engines themselves.

Furthermore, I am skeptical as to whether or not it's possible to implement syntax highlighting within ES2015 template strings without having to infer the syntax type from the name of the tag. I don't think there's a single parser out there that can do this yet.

I'm not saying it's _impossible_, but probably not worth the time when there are already technologies out there far better suited to the task. Take [t7](https://github.com/trueadm/t7) for example - it's a virtual DOM templating engine that uses ES2015 tagged templates as an _interface_ to the developer, but it too suffers from being far too verbose and lack of proper syntax highlighting.
