### ISSUE TITLE
Remove `babel-runtime` dependency

### ISSUE THREAD

**Issue by anton-rudeshko** [declandewet/common-tags#26]
Is there any way to use your library without pulling babel? Kinda wierd.

**Comment by declandewet** [comment]
Hi @anton-rudeshko - while I would love to get rid of any runtime dependencies, I'm afraid this is not possible without extraneous work. It's a bit too early to ship this module without compiling it first, as there is no guarantee that the syntax I use is compatible with all the different Babel configs people tend to use. `babel-runtime` is listed as a module dependency to avoid each file from becoming too bloated with inlined babel helpers - I'd rather just reference these from `babel-runtime`. I hope it isn't causing any issues for you!

**Comment by anton-rudeshko** [comment]
I'd love to use your library, but babel-runtime is a blocker for me right now.

What do you think if I try to make your module more backward compatible?
BTW, why there is a restriction on `npm >= 3.0.0`?

**Comment by declandewet** [comment]
> I'd love to use your library, but babel-runtime is a blocker for me right now.

Why?

> What do you think if I try to make your module more backward compatible?

I welcome all contributions :)

> BTW, why there is a restriction on `npm >= 3.0.0`?

It's not a restriction, it's a recommendation `common-tags` _should_ work without it, but I've experienced a few Babel-transpiled ES2015+ modules break without it -
