### ISSUE TITLE
More generic name for `html` tag?

### ISSUE THREAD

**Issue by yortus** [declandewet/common-tags#33]
I came across this library via [2ality](http://www.2ality.com/2016/05/template-literal-whitespace.html). Thanks for this great collection of problem solvers!

My main use is for the `html` tag - but my template contains JavaScript source code, not HTML. In fact the `html` tag is pretty useful while generating any block-structured code with correct indenting.

It looks a little strange and not so self-documenting to see JavaScript source inside a `html` tagged template. At present I just import it using something like `import {html as js} from 'common-tags'`, but it also looks a bit odd seeing `html` there.

So, I was wondering if this tag could have a more generic name (or at least an alias) exported from the library itself?

**Comment by declandewet** [comment]
Hi @yortus - glad you're enjoying the library! Sure, I can get down with adding an alias. Perhaps `source` or `structured`?

**Comment by yortus** [comment]
Great. `source` sounds good, or maybe `codeBlock`.

**Comment by declandewet** [comment]
@yortus - I've added `source` and `codeBlock` aliases for the `html` tag in  #35. This is published on NPM as `v1.2.0`

**Comment by yortus** [comment]
That's awesome, thanks @declandewet!
