### ISSUE TITLE
Investigate compile-time evaluation

### ISSUE THREAD

**Issue by declandewet** [declandewet/common-tags#40]

**Comment by declandewet** [comment]
Would be a great feature but don't have the time to learn the compiler-fu necessary to implement it.

**Comment by Telokis** [comment]
Just commenting to say that this issue would be very nice to have.
Adding run-time processing in order to clean the source code is not acceptable for my company even though I tried very hard to convince them!

**Comment by fatfisz** [comment]
This definitely goes out of scope of this package - it would be best done as a Babel plugin or a macro. Even then not everything can be done during compilation time - if you're using variables inside a template, then they are inaccessible during compilation.

I think that's the main question that needs to be answered here - what should the plugin do when it encounters variables? Possible solutions:
1. Replace with the library call and handle during runtime
2. Do 1. and print a warning (possibly enabled by a flag that would be enabled in development)
3. Throw an error "Unable to process this in compilation time. Please use the runtime library."

**Comment by declandewet** [comment]
@Telokis I would love to have this be an option but it's just not a realistic goal. I don't do any work that requires massive performance optimisation and I'm not confident in my own ability to add this as a feature, so I won't be adding it. If you're up to it though, you could create a separate Babel plugin that transpiles an AST with some of the core `common-tags` tag identifiers to the expected output.

@fatfisz It most definitely is possible to handle variables - but only for the less involved tags like `stripIndent` or `oneLine`. I agree that it should be a separate tool though.
