### ISSUE TITLE
use jsnext:main to expose modern JS syntax, pre-babel for 4.x

### ISSUE THREAD

**Issue by scottnonnenberg** [declandewet/common-tags#45]
More information: https://github.com/rollup/rollup/wiki/jsnext:main

And then anyone doing a normal Node.js require, say in 4.x, would no longer be forced into loading `babel-runtime` into their production processes.

I was just about to recommend this library to my network, but that runtime dependency is a deal-breaker.

Really, I'd recommend that you `babel` down to lowest common denominator (ES5) to make it easier for users to webpack their components. The standard `webpack`/`babel` configuration excludes `node_modules`: https://github.com/babel/babel-loader#usage

**Comment by declandewet** [comment]
You're not the first to suggest this: #26 

I can look into it, but it would require some effort, and my time for OSS is pretty limited. I'll have to read more into `jsnext:main` - but this seems `rollup` specific.

You are more than welcome to get the ball rolling with a pull request, though! ❤️
