### ISSUE TITLE
`source` doesn't seem to work when put into a new template literal?

### ISSUE THREAD

**Issue by zaynv** [declandewet/common-tags#56]
Here is my current code:

``` javascript
function generateFruits () {
  const fruits = [
    {
      name: 'apples',
      quantity: 3
    },
    {
      name: 'oranges',
      quantity: 2
    }
  ]

  return source`
    Fruits
      ${fruits.map(f => `${f.name}: ${f.quantity}`)}
  `
}
```

If I do `console.log(generateFruits())`, I get the expected output:

```
Fruits
  apples: 3
  oranges: 2
```

However, if I create a variable called `template` and use `generateFruits()` inside of there, it doesn't seem to work:

``` javascript
const template = stripIndent`
  ${generateFruits()}
`
```

I thought that this would give the same output, but instead it seems to give this:

```
Fruits
apples: 3
oranges: 2
```

And if I remove the `stripIndent`, it gives this:

```
  Fruits
  apples: 3
  oranges: 2
```

Why does using `generateFruits()` inside a different template literal make it lose the indentation?

**Comment by declandewet** [comment]
Hi @zaynv - so sorry I couldn't respond sooner!

I have a hunch this is to do with the way template tags work - some can be nested, some cannot - depending on the logic performed in the tag. This case is an example of the latter: `stripIndent` trims surrounding whitespace, then processes substitutions - so it's likely that this is correct output. I however am not 100% certain, so I will investigate it when I have some time.

**Comment by fatfisz** [comment]
This might be related: #109.

**Comment by fatfisz** [comment]
It turns out this was related. The reason for the code not working as expected is that `sourceIndent` does not indent multiline strings from substitutions, unlike `source`. What would work instead is using the `source` tag again:

```js
const template = source`
  ${generateFruits()}
`
```

This might be misleading, so I added a note to the docs.
